apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "hello"
  namespace: "default"
  labels:
    app: "hello-app"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "hello-app"
  template:
    metadata:
      labels:
        app: "hello-app"
    spec:
      containers:
      - name: "hello-app"
        image: "gcr.io/GOOGLE_CLOUD_PROJECT/gke-image/myimage:COMMIT_SHA
---
kind: Service
apiVersion: v1
metadata:
  name: hello
spec:
  selector:
    app: hello-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8090
  type: LoadBalancer